"""empty message

Revision ID: b5cb6a8c676e
Revises: 
Create Date: 2020-01-21 14:33:37.448748

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'b5cb6a8c676e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_queue',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('message', sa.String(length=20000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_link',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('public', sa.String(length=10000), nullable=True),
    sa.Column('private', sa.String(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=40), nullable=False),
    sa.Column('city', sa.SmallInteger(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_user'), 'profile', ['user'], unique=True)
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=1000000), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['profile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['profile.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_index(op.f('ix_profile_user'), table_name='profile')
    op.drop_table('profile')
    op.drop_table('password_link')
    op.drop_table('message_queue')
    # ### end Alembic commands ###
